// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package v1

import (
	"github.com/google/wire"
	"server/pkg/api/handler"
	v1_2 "server/pkg/api/handler/v1"
	"server/pkg/dao/v1"
	"server/pkg/db"
	"server/pkg/service/v1"
)

// Injectors from wire.go:

// newApiHandler 创建 API 处理器实例
func newApiHandler() handler.ApiHandlerInterface {
	gormDB := db.GetDB()
	apiDaoInterface := v1.NewApiDao(gormDB)
	casbinDaoInterface := v1.NewCasbinDao(gormDB)
	authorityDaoInterface := v1.NewAuthorityDao(gormDB)
	transaction := db.NewGormTxManager(gormDB)
	apiServiceInterface := system.NewApiService(apiDaoInterface, casbinDaoInterface, authorityDaoInterface, transaction)
	apiHandlerInterface := v1_2.NewApiHandler(apiServiceInterface)
	return apiHandlerInterface
}

// newAuthorityHandler 创建权限处理器实例
func newAuthorityHandler() handler.AuthorityHandlerInterface {
	gormDB := db.GetDB()
	authorityDaoInterface := v1.NewAuthorityDao(gormDB)
	menuDaoInterface := v1.NewMenuDao(gormDB)
	casbinDaoInterface := v1.NewCasbinDao(gormDB)
	transaction := db.NewGormTxManager(gormDB)
	authorityServiceInterface := system.NewAuthorityService(authorityDaoInterface, menuDaoInterface, casbinDaoInterface, transaction)
	authorityHandlerInterface := v1_2.NewAuthorityHandler(authorityServiceInterface)
	return authorityHandlerInterface
}

// newCasbinHandler 创建策略处理器实例
func newCasbinHandler() handler.CasbinHandlerInterface {
	gormDB := db.GetDB()
	apiDaoInterface := v1.NewApiDao(gormDB)
	casbinDaoInterface := v1.NewCasbinDao(gormDB)
	authorityDaoInterface := v1.NewAuthorityDao(gormDB)
	transaction := db.NewGormTxManager(gormDB)
	casbinServiceInterface := system.NewCasbinService(apiDaoInterface, casbinDaoInterface, authorityDaoInterface, transaction)
	casbinHandlerInterface := v1_2.NewCasbinHandler(casbinServiceInterface)
	return casbinHandlerInterface
}

// newJwtHandler 创建 JWT 处理器实例
func newJwtHandler() handler.JwtHandlerInterface {
	gormDB := db.GetDB()
	transaction := db.NewGormTxManager(gormDB)
	jwtDaoInterface := v1.NewJwtDao(gormDB)
	userDaoInterface := v1.NewUserDao(gormDB)
	jwtServiceInterface := system.NewJwtService(transaction, jwtDaoInterface, userDaoInterface)
	jwtHandlerInterface := v1_2.NewJwtHandler(jwtServiceInterface)
	return jwtHandlerInterface
}

// newMenuHandler 创建菜单处理器实例
func newMenuHandler() handler.MenuHandlerInterface {
	gormDB := db.GetDB()
	menuDaoInterface := v1.NewMenuDao(gormDB)
	authorityDaoInterface := v1.NewAuthorityDao(gormDB)
	transaction := db.NewGormTxManager(gormDB)
	menuServiceInterface := system.NewMenuService(menuDaoInterface, authorityDaoInterface, transaction)
	menuHandlerInterface := v1_2.NewMenuHandler(menuServiceInterface)
	return menuHandlerInterface
}

// newUserHandler 创建用户处理器实例
func newUserHandler() handler.UserHandlerInterface {
	gormDB := db.GetDB()
	transaction := db.NewGormTxManager(gormDB)
	jwtDaoInterface := v1.NewJwtDao(gormDB)
	userDaoInterface := v1.NewUserDao(gormDB)
	jwtServiceInterface := system.NewJwtService(transaction, jwtDaoInterface, userDaoInterface)
	userServiceInterface := system.NewUserService(jwtServiceInterface, userDaoInterface, jwtDaoInterface, transaction)
	userHandlerInterface := v1_2.NewUserHandler(userServiceInterface)
	return userHandlerInterface
}

// wire.go:

// 数据库连接 Provider
var DBProvider = wire.NewSet(db.GetDB, db.NewGormTxManager)
