package errcode

func init() {
	NewErrCode(ErrUserNotFound, 404, "用户不存在")
	NewErrCode(ErrUserPasswordFault, 404, "密码错误")
	NewErrCode(ErrUserAlreadyExist, 400, "用户已存在")
	NewErrCode(ErrUserForbidden, 400, "用户被冻结")
	NewErrCode(ErrUserRegisteFailed, 400, "用户注册失败")
	NewErrCode(ErrUserGetList, 400, "获取用户列表失败")
	NewErrCode(ErrUserSwitchRole, 400, "切换用户权限失败")
	NewErrCode(ErrUserSetAuthorities, 400, "权限设置失败")
	NewErrCode(ErrUserDeleteSelf, 400, "禁止删除当前用户")
	NewErrCode(ErrUserDeleteFailed, 400, "删除用户失败")
	NewErrCode(ErrUserSetInfoFailed, 400, "设置用户信息失败")
	NewErrCode(ErrUserSetSelfFailed, 400, "设置信息失败")
	NewErrCode(ErrUserResetPassworkFailed, 400, "重置密码失败")
	NewErrCode(ErrReachMaxCount, 400, "Secret 已达最大次数")
	NewErrCode(ErrSecretNotFound, 404, "Secret 不存在")
	NewErrCode(ErrSuccess, 200, "OK")
	NewErrCode(ErrUnknown, 500, "内部服务器错误")
	NewErrCode(ErrBind, 400, "请求体参数绑定错误")
	NewErrCode(ErrValidation, 400, "验证失败")
	NewErrCode(ErrErrTokenInvalid, 401, "Token 不可用")
	NewErrCode(ErrTokenParseFailed, 401, "Token 解析错误")
	NewErrCode(ErrInternalServer, 500, "内部服务器异常")
	NewErrCode(ErrDatabase, 500, "数据库错误")
	NewErrCode(ErrEncrypt, 401, "密码加密错误")
	NewErrCode(ErrSignatureInvalid, 401, "签名无效")
	NewErrCode(ErrExpired, 401, "Token 已过期")
	NewErrCode(ErrTokenRevokeFailed, 401, "JWT作废失败")
	NewErrCode(ErrTokenRedisStateSetFailed, 401, "设置登录状态失败")
	NewErrCode(ErrTokenCreateFailed, 401, "生成JWT失败")
	NewErrCode(ErrInvalidAuthHeader, 401, "Authorization 头格式错误")
	NewErrCode(ErrMissingHeader, 401, "The `Authorization` header was empty")
	NewErrCode(ErrPasswordIncorrect, 401, "原密码和当前密码不符")
	NewErrCode(ErrPermissionDenied, 403, "权限不足")
	NewErrCode(ErrCasbinSet, 400, "权限设置失败")
	NewErrCode(ErrEncodingFailed, 500, "编码失败")
	NewErrCode(ErrDecodingFailed, 500, "解码失败")
	NewErrCode(ErrInvalidJSON, 500, "JSON 格式错误")
	NewErrCode(ErrEncodingJSON, 500, "JSON 编码错误")
	NewErrCode(ErrDecodingJSON, 500, "JSON 解码错误")
	NewErrCode(ErrInvalidYaml, 500, "Yaml 格式错误")
	NewErrCode(ErrEncodingYaml, 500, "Yaml 编码错误")
	NewErrCode(ErrDecodingYaml, 500, "Yaml 解码错误")
	NewErrCode(ErrLimitedIP, 500, "请求频繁")
	NewErrCode(ErrTooManyRequests, 401, "服务器繁忙, 请等待")
	NewErrCode(ErrGetAuthorities, 500, "获取授权列表错误")
	NewErrCode(ErrAuthorityNotFound, 404, "权限不存在")
	NewErrCode(ErrAuthorityAlreadyExist, 400, "权限已经存在")
	NewErrCode(ErrAuthorityCreateFailed, 400, "权限创建失败")
	NewErrCode(ErrAuthorityDeleteFailed, 400, "权限删除失败")
	NewErrCode(ErrAuthorityUpdateFailed, 400, "权限更新失败")
	NewErrCode(ErrAuthoritySearchFailed, 400, "权限查询失败")
	NewErrCode(ErrAuthorityAlreadyAssignedToUser, 400, "权限已分配到用户")
	NewErrCode(ErrAuthorityHasChildren, 400, "权限包含子权限")
	NewErrCode(ErrAuthorityNotPermissionGet, 403, "当前用户无权限")

	// 需要反馈到前端的错误，不需要记录到日志
	{
		NewErrCode(ErrMenuNotFound, 200, "菜单不存在")
		NewErrCode(ErrMenuAlreadyExist, 200, "重复菜单名称")
		NewErrCode(ErrAuthorityMenuNotFound, 200, "权限ID没有对应的授权菜单")
		NewErrCode(ErrMenuSetFailed, 200, "菜单设置失败")
		NewErrCode(ErrMenuHasChildren, 200, "此菜单存在子菜单不可删除")
		NewErrCode(ErrMenuAsHomePage, 200, "此菜单有角色正在作为首页，不可删除")
		NewErrCode(ErrMenuSetHomePageFailed, 200, "菜单设置首页失败")
		NewErrCode(ErrMenuDeleteFailed, 200, "菜单删除失败")
	}

	// Api相关错误
	{
		NewErrCode(ErrApiNotFound, 404, "Api不存在")
		NewErrCode(ErrApiAlreadyExist, 400, "Api已存在")
		NewErrCode(ErrApiCreateFailed, 400, "Api创建失败")
		NewErrCode(ErrApiDeleteFailed, 400, "Api删除失败")
		NewErrCode(ErrApiUpdateFailed, 400, "Api更新失败")
		NewErrCode(ErrApiIgnoreFailed, 400, "Api忽略失败")
		NewErrCode(ErrApiSyncFailed, 400, "Api同步失败")
		NewErrCode(ErrApiRegisterListFailed, 400, "获取Api注册列表失败")
		NewErrCode(ErrApiGroupFailed, 400, "获取Api分组失败")
		NewErrCode(ErrApiSyncParamsFailed, 400, "Api同步失败")
	}
}
